# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/77855f0f-5e1a-4a7f-9d7d-8a0410cc7012";

  fileSystems."/".device = "/dev/mapper/crypted";
  fileSystems."/".fsType = "ext4";


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/10D2-1844";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3ac6f24a-bbc0-49e9-b849-4157e51c7c7c"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
